# docker build --network host -t tor .
# docker run -d --name tor -p 9050:9050 tor
FROM alpine:latest

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories 

RUN apk update
RUN apk upgrade
RUN apk add tor obfs4proxy

RUN echo 'SocksPort 0.0.0.0:9050' >> /etc/tor/torrc
RUN chown -R tor /etc/tor

CMD ["tor"]
